version: "3.8"

services:
  web:
    container_name: boiler-web
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3417:3417"
    networks:
      - application

networks:
  application:
    driver: bridge

volumes:
  web:
    driver: local
